apiVersion: v1
kind: Service
metadata:
  name: backend-service # Nom utilisé dans la config Nginx !
spec:
  type: ClusterIP # Uniquement accessible depuis le cluster
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080